export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const SUBMIT_ORDER_AUTH = 'SUBMIT_ORDER_AUTH';
export const SUBMIT_ORDER_UNAUTH = 'SUBMIT_ORDER_UNAUTH';
